FROM openjdk:11-jre
COPY . /CTC-LocalApp-CLI/API/local-app/target/local-app-1.0-SNAPSHOT-jar-with-dependencies.jar/
#RUN chmod 777 . /ScriptShell/animix-data-colection-CLI/animix/target/animix-data-colection-CLI/animix/target/
#CMD ["java", "-jar", "local-app-1.0-SNAPSHOT-jar-with-dependencies.jar"]